### ISSUE TITLE
exprs<-  not working anymore

### ISSUE THREAD

**Issue by StephaneKazmierczak** [Bioconductor/Biobase#1]
Hi, I am having some issue with version Biobase 2.38.0 
while doing :

exp <- exprs(gse)
exprs(gse)<- exp 

I am now getting the following error:
Error in (function (od, vd)  : 
  object and replacement value dimnames differ

**Comment by mtmorgan** [comment]
Likely you have loaded a tidyverse package with a conflicting definition of `exprs()`. Either don't load those packages or fully resolve function names
```
exp <- Biobase::exprs(gse)
Biobase::exprs(gse) <- exp
```

**Comment by StephaneKazmierczak** [comment]
Thank for the response, you are right I do load tidyverse but I am also using :
ex <- Biobase::exprs(gse)
Biobase::exprs(gse) <- ex
with the same error

**Comment by mtmorgan** [comment]
Please provide a reproducible example. For instance, in a new R session and using packages that we all have access to I can do
```
library(ALL)
data(ALL)
exprs(ALL) = exprs(ALL)
```
Please also report your sessionInfo(). I have
```
> sessionInfo()
R version 3.5.1 Patched (2018-08-20 r75173)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /home/mtmorgan/bin/R-3-5-branch/lib/libRblas.so
LAPACK: /home/mtmorgan/bin/R-3-5-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] ALL_1.22.0          Biobase_2.40.0      BiocGenerics_0.26.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1   
```
Please also make sure that your current combination of packages is from the same installation of Bioconductor
```
> BiocInstaller::biocValid()
TRUE
```

**Comment by StephaneKazmierczak** [comment]
Sorry for the trouble I think I found my mistake, 
My gse object was not valide to start with, using validObject(gse) returned an error 
I was creating the gse setting the phenotype with pData<- 
which didn't alert me about the difference of sampleNames between assaydata and phenodata

**Comment by Pointillomic** [comment]
In case it is helpful for people, one possible cause of this error is that rownames are lost during operations on the data (eg on join operations in my case). Pulling out rownames as a column, performing the join, and then putting the column back as rownames fixed the issue for me (and validObjects is a great way to quickly check things are fine as noted above)
