### ISSUE TITLE
Biobase bugs since new R version (4.0)

### ISSUE THREAD

**Issue by EmmaRuiz** [Bioconductor/Biobase#6]
Good morning,

I have a issue with Biobase inside clValid function (clValid package) since I updated R (new version= 4.0).
Below is the error that I obtain :

Error in switch(class(obj), matrix = mat <- obj, ExpressionSet = mat <- Biobase::exprs(obj),  : 
  EXPR doit être un vecteur de longueur 1

The data that I use is a numeric dataframe. Even when I transformed it in a matrix, I obtained the same error.

I try this step that I saw in of the other issues : 
exp <- Biobase::exprs(score.SPA.PROGvsPRE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘exprs’ for signature ‘"matrix"

I check if my object for clValid was valid with validObject(score.SPA.PROGvsPRE), and it's valid.

I try to update Biobase but nothing changes, I have the same problem.

Thank you for your help

Emmanuelle

**Comment by mtmorgan** [comment]
This is a problem with the clValid package, `clValid()` function, where

```
switch(class(obj), ...
```

fails because in R-3.6 and earlier, 
```
> class(matrix())
[1] "matrix"
```

whereas in R 4.0

```
> class(matrix())
[1] "matrix" "array"
```

This is an issue for the clValid package maintainer to address, not for Biobase. Please try and contact

```
> maintainer('clValid')
[1] "Vasyl Pihur <vpihur@gmail.com>"
```
