### ISSUE TITLE
superclass "characterORconnection" not defined in the environment of the object's class

### ISSUE THREAD

**Issue by mbstadler** [Bioconductor/Biobase#7]
I hope this is the right place to post this issue (please let me know if I should direct it somewhere else):

SInce ~July 22nd, `R CMD check` fails for my Bioconductor package `QuasR` (see e.g. https://github.com/fmicompbio/QuasR/actions/runs/232719578), but only on macOS and not on Linux.
On the Bioconductor builders, `QuasR` checks fine on all platforms.

The error is reproducible also on my personal macOS laptop, and the traceback shows a call from `QuasR::preprocessReads` to `Biobase::mkScalar`. Using the `Biobase::mkScalar` with a character argument, the error can be triggered in a fresh R session:
```
library(Biobase)
mkScalar("test")
```
which results in the same kind of error that I see on my laptop and on github for the `QuasR` package:
```
Error in validObject(.Object) : 
  invalid class “ScalarCharacter” object: superclass "characterORconnection" not defined in the environment of the object's class
```

The error persists if I start with a clean R/Bioconductor installation.
Is it possible that there were recent changes to these classes that may have triggered it?
It's unclear to me why the error only presents it self on some systems, but not on others.

Here is my session info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Biobase_2.49.0      BiocGenerics_0.35.4

loaded via a namespace (and not attached):
[1] compiler_4.0.2
```

**Comment by mtmorgan** [comment]
I think this is because R caches S4 methods and classes at _package installation time_. You could test this by creating a new library
```
$ mkdir /tmp/lib
$ R_LIBS_USER=/tmp/lib R --vanilla()
> sapply(.libPaths(), function(x) length(dir(x)))
                       /private/tmp/lib /Users/ma38727/bin/R-4-0-branch/library
                                      0                                      30
```
where the only packages are the base and recommended packages. Then
```
install.packages("BiocManager", repos="https://cran.r-project.org")
BiocManager::install(version="devel")
BiocManager::install("Biobase")
Biobase::mkScalar("test")
##  "test"
```
If this is the case, then it would seem that BiocGenerics and / or Biobase needs to be re-installed on the macOS builder...

**Comment by mbstadler** [comment]
Thanks @mtmorgan for the quick reply.

The cache would explain why things run smoothly on the builders, but it's strange that the above works for you without error using freshly installed packages. I have run the exact same code from your reply, I also get:
```
> sapply(.libPaths(), function(x) length(dir(x)))
                                              /private/tmp/lib 
                                                             0 
/Library/Frameworks/R.framework/Versions/4.0/Resources/library 
                                                            30 
```
but in my case, on macOS, `Biobase::mkScalar("test")` throws the error (just like the macOS runner on github actions):
```
Fehler in validObject(.Object) : 
  invalid class “ScalarCharacter” object: superclass "characterORconnection" not defined in the environment of the object's class
```
On Linux, things are working fine, though.

**Comment by mtmorgan** [comment]
I'd guess that you're installing 'binary' packages, and the binaries are from the builder, and the builder has stale binaries, whereas I'm installing from source so get a truly fresh install. Let's see if we can't get some clarification from @hpages

**Comment by mbstadler** [comment]
I can confirm that when installing `Biobase` on macOS from sources, there is no error for `Biobase::mkScalar("test")` anymore.

**Comment by hpages** [comment]
I just bumped Biobase version from 2.49.0 to 2.49.1 in devel in order to trigger rebuilt and propagation of new Windows & Mac binaries. The new binaries should go online on Friday afternoon.

Let us know if they solve the problem. Thanks!

**Comment by mbstadler** [comment]
I just successfully ran `R CMD check` on macOS using the new binary fro Biobase 2.49.1. Thanks a lot!
